import type { BundledPlugin } from "../types/plugin.test.types";

export const BUNDLED_DEFAULT_PLUGINS: BundledPlugin[] = [
  {
    pluginId: "7f7207f2-ed04-4e49-a566-6ed244dea111",
    pluginType: "validation",
    pluginName: "default-schema",
    pluginVersion: "1.2.0",
    pluginMinioObjectPath: null,
    securityLevel: "medium",
    config: {},
    notes: "Bundled default schema plugin",
    status: "active",
    bundledSourcePath: "src/default-plugins/schema/default.schema.js",
    isBundled: true,
  },
  {
    pluginId: "bb71232f-0d94-42b6-bca7-792eb954690e",
    pluginType: "validation",
    pluginName: "default-schema",
    pluginVersion: "1.1.0",
    pluginMinioObjectPath: null,
    securityLevel: "medium",
    config: {},
    notes: "Bundled deprecated schema plugin",
    status: "deprecated",
    bundledSourcePath: "src/default-plugins/schema/default.schema.1.1.0.js",
    isBundled: true,
  },
  {
    pluginId: "fbabe1c3-f563-4634-bb41-da53f88e6cf8",
    pluginType: "mapping",
    pluginName: "default-mapper",
    pluginVersion: "1.2.0",
    pluginMinioObjectPath: null,
    securityLevel: "medium",
    config: {},
    notes: "Bundled default mapper plugin",
    status: "active",
    bundledSourcePath: "src/default-plugins/mapper/default.mapper.js",
    isBundled: true,
  },
  {
    pluginId: "6f31845c-41f9-422c-a773-d5a37d7eae2e",
    pluginType: "storage",
    pluginName: "default-storage",
    pluginVersion: "1.2.0",
    pluginMinioObjectPath: null,
    securityLevel: "medium",
    config: {},
    notes: "Bundled default storage plugin",
    status: "active",
    bundledSourcePath: "src/default-plugins/storage/default.storage.js",
    isBundled: true,
  },
  {
    pluginId: "83d52575-ecf6-4d86-aa8f-30480f883a5b",
    pluginType: "outpost",
    pluginName: "default-outpost",
    pluginVersion: "1.0.0",
    pluginMinioObjectPath: null,
    securityLevel: "medium",
    config: {},
    notes: "Bundled default outpost plugin",
    status: "active",
    bundledSourcePath: "src/default-plugins/outpost/default.outpost.js",
    isBundled: true,
  },
];
