import * as utils from  '../../utils.js';
import { expect } from 'chai';

describe('OpenLDR Supported Content Type Test', function() {
  this.timeout(60000);

  let token;

  before(async function() {
    // Get authentication token
    const credentials = utils.credentialPairs[0];
    token = await utils.getToken(credentials.clientId, credentials.clientSecret);
  });

  describe('Authentication', function() {
    it('should obtain authentication token successfully', function() {
      expect(token).to.not.be.empty;
    });
  });

  describe('Message Sending', function() {
    it('should test HL7 v2 content type', async function() {        
        const data = `MSH|^~\\&|KAMPALA_LIMS|KAMPALA_HOSP|OPENLDR|OPENLDR_SYS|20240703160000||ORU^R01^ORU_R01|TEST001|P|2.5|||AL|AL|UG
PID|1||P54321^^^KAMPALA_HOSP^MR||SMITH^JOHN^A||19850615|M|||456 KAMPALA AVE^^KAMPALA^CENTRAL^256^UG||(256)701234568|EN|M|UG|54321|||UG
OBR|1|ORD002|LAB002|AFR_HIV_001^HIV Test^RUVOS||20240703160000|20240703160000|||||||20240703160000||NAMUGGA^MARY^DR|||20240703163000|||F
OBX|1|ST|AFR_HIV_001^HIV^RUVOS||NEGATIVE||POS|||F|||20240703163000
`;
        const response = await utils.sendTestMessage(token, data, 'application/hl7-v2');
        expect(response).to.have.property('message').and.to.be.equal('Message successfully processed.');
    });

    it('should test XML content type', async function() {        
        const data = `<?xml version="1.0" encoding="UTF-8"?>
<LabResult>
    <MessageId>XML001</MessageId>
    <Timestamp>2024-07-03T16:00:00Z</Timestamp>
    <Facility>KAMPALA_HOSP</Facility>
    <Patient>
        <Id>P99999</Id>
        <Name>Jane Doe</Name>
        <DOB>1990-03-15</DOB>
    </Patient>
    <Test>
        <Code>MALARIA_TEST</Code>
        <Result>POSITIVE</Result>
        <Date>2024-07-03</Date>
    </Test>
</LabResult>
`;
        const response = await utils.sendTestMessage(token, data, 'application/xml');
        expect(response).to.have.property('message').and.to.be.equal('Message successfully processed.');
    });

    it('should test CSV content type', async function() {        
        const data = `patient_id,test_type,result,date,technician
P001,HIV_VL,<200 copies/mL,2024-07-01,Sarah J
P002,MALARIA,POSITIVE,2024-07-02,Mike C
P003,TB_PCR,NEGATIVE,2024-07-03,Anna K
P004,COVID_AG,POSITIVE,2024-07-03,Tom B
`;
        const response = await utils.sendTestMessage(token, data, 'text/csv');
        expect(response).to.have.property('message').and.to.be.equal('Message successfully processed.');
    }); 

    it('should test FHIR JSON content type', async function() {        
        const data = {
            resourceType: "Bundle",
            id: "lab-bundle-001",
            type: "message",
            timestamp: "2024-07-03T16:00:00Z",
            entry: [
                {
                    resource: {
                        resourceType: "DiagnosticReport",
                        id: "hiv-test-001",
                        status: "final",
                        category: [
                            {
                                coding: [
                                    {
                                        system: "http://terminology.hl7.org/CodeSystem/v2-0074",
                                        code: "LAB",
                                        display: "Laboratory"
                                    }
                                ]
                            }
                        ],
                        code: {
                            coding: [
                                {
                                    system: "http://loinc.org",
                                    code: "33747-0",
                                    display: "HIV 1 and 2 tests"
                                }
                            ]
                        },
                        conclusion: "NEGATIVE"
                    }
                }
            ]
        };

        const response = await utils.sendTestMessage(token, data, 'application/fhir+json');
        expect(response).to.have.property('message').and.to.be.equal('Message successfully processed.');
    }); 

    it('should test plain text content type', async function() {        
        const data = `=== LABORATORY REPORT ===
Date: 2024-07-03
Facility: Kampala Hospital
Patient: John Smith (ID: P12345)
Doctor: Dr. Sarah Nakato

TESTS PERFORMED:
- HIV Viral Load: <200 copies/mL (UNDETECTABLE)
- CD4 Count: 450 cells/μL (NORMAL)
- Hemoglobin: 12.5 g/dL (NORMAL)

INTERPRETATION:
HIV viral load undetectable. Continue current therapy.
Patient shows good immunological recovery.

Report generated by: Lab Technician Mary Namugga
`;
        const response = await utils.sendTestMessage(token, data, 'text/plain');
        expect(response).to.have.property('message').and.to.be.equal('Message successfully processed.');
    });

    it('should test PDF content type', async function() {        
        const data = Buffer.from([0x25, 0x50, 0x44, 0x46, 0x2D, 0x31, 0x2E, 0x34, 0x0A]);

        const response = await utils.sendTestMessage(token, data, 'application/pdf');
        expect(response).to.have.property('message').and.to.be.equal('Message successfully processed.');
    });
  });

});