#!/bin/sh
set -e

# Substitute environment variables
envsubst '${KEYCLOAK_HOSTNAME} ${KEYCLOAK_BASE_URL} ${KEYCLOAK_REALM} ${KEYCLOAK_CLIENT_ID} ${KEYCLOAK_CLIENT_SECRET} ${ENTITY_SERVICES_PORT} ${ENTITY_SERVICES_HOSTNAME} ${ENTITY_SERVICES_PORT} ${MINIO_HOSTNAME} ${OPENSEARCH_HOSTNAME} ${OPENSEARCH_DASHBORD_HOSTNAME} ${KAFKA_HOSTNAME} ${KAFKA_CONNECT_HOSTNAME} ${KAFKA_CONDUKTOR_HOSTNAME} ${DATA_PROCESSING_HOSTNAME} ${DATA_PROCESSING_PORT} ${EXTERNAL_DATABASE_HOSTNAME} ${EXTERNAL_DATABASE_PORT} ${STUDIO_HOSTNAME} ${STUDIO_PORT} ${AI_HOSTNAME} ${AI_PORT} ${WEB_HOSTNAME} ${WEB_PORT} ${GATEWAY_HTTP_PORT} ${GATEWAY_HTTPS_PORT}' \
  < /tmp/nginx/nginx.conf.template \
  > /etc/nginx/nginx.conf

# Test nginx configuration
nginx -t

# Start nginx
nginx

exec nginx-ui -config /etc/nginx-ui/app.ini